import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://www.sundarisilks.com/cdn/shop/articles/handicrafts-india-part-one-cover.png?v=1619175105",
    title: "Indian Handicraft Couple Dolls",
    star: <AiFillStar className="rating-star" />,
    reviews: "(189 reviews)",
    prevPrice: "600",
    newPrice: "4500",
    company: "Harikishan",
    color: "multicolour",
    category: "Handicrafts",
  },
  {
    img: "https://www.mrignayanikolkata.com/wp-content/uploads/2019/03/craft8-1.jpg",
    title: "Designed Kolkatta Pots",
    star: <AiFillStar className="rating-star" />,
    reviews: "(167 reviews)",
    prevPrice: "900",
    newPrice: "700",
    company: "Shubrajyothi",
    color: "white and brown",
    category: "Pots",
  },

  {
    img: "https://res.cloudinary.com/purnesh/image/upload/w_540,f_auto,q_auto:eco,c_limit/indian-handicrafts-emporium0.jpg",
    title: "Designer Vase",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "1000",
    newPrice: "900",
    company: "Shubrajyothi",
    color: "white",
    category: "Pots",
  },
  {
    img: "https://img.traveltriangle.com/blog/wp-content/uploads/2022/01/Rajasthan-Handicrafts-400x229.jpg",
    title: "Designer Wall Hanging",
    star: <AiFillStar className="rating-star" />,
    reviews: "(100 reviews)",
    prevPrice: "600",
    newPrice: "550",
    company: "Harikishan",
    color: "Multicolour",
    category: "Handicrafts",
  },
  {
    img: "https://gaatha.com/wp-content/webpc-passthru.php?src=https://gaatha.com/wp-content/uploads/2023/05/handmade-gujarati-fan-520x408.jpg&nocache=1",
    title: "Wall Hanging",
    star: <AiFillStar className="rating-star" />,
    reviews: "(113 reviews)",
    prevPrice: "500",
    newPrice: "100",
    company: "Harikishan",
    color: "Blue and White",
    category: "Handicrafts",
  },
  {
    img: "https://www.handicraftsindia.org/wp-content/uploads/2010/05/Blue-Pottery3-410x320.jpg",
    title: "Pot Dinner Set",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "2500",
    newPrice: "2400",
    company: "Shubrajyothi",
    color: "Blue",
    category: "Pots",
  },

  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSclZkxw9J73LGOGGDEDFCBdn98LuevbAEXOA&usqp=CAU",
    title: "Amrut Sandal Soap",
    star: <AiFillStar className="rating-star" />,
    reviews: "(103 reviews)",
    prevPrice: "300",
    newPrice: "250",
    company: "Sandal Factory",
    color: "Gold",
    category: "Cosmetics",
  },

  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZHDnAEKQWTubc90VJOKwMCo1rgZ-9PDbHVA&usqp=CAU",
    title: "Mysore Sandal Soap",
    star: <AiFillStar className="rating-star" />,
    reviews: "(19 reviews)",
    prevPrice: "350",
    newPrice: "300",
    company: "Sandal Factory",
    color: "Gold",
    category: "Cosmetics",
  },

  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXoXFI9o_xoRPMG1wazYWKwYUmCviCxfJdsQ&usqp=CAU",
    title: "Multani Mitti",
    star: <AiFillStar className="rating-star" />,
    reviews: "(190 reviews)",
    prevPrice: "800",
    newPrice: "275",
    company: "Multani Mitti",
    color: "brown",
    category: "Cosmetics",
  },

  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTz3Ta8xepZEExXyg0VNwPL1RiA3wFJal7TSA&usqp=CAU",
    title: "Agarbatti",
    star: <AiFillStar className="rating-star" />,
    reviews: "(103 reviews)",
    prevPrice: "300",
    newPrice: "150",
    company: "Cycle",
    color: "red",
    category: "Household",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6GLgmPO5xfN0kYe9vaG65L2Mkllda9QCLlQ&usqp=CAU",
    title: "Camphor",
    star: <AiFillStar className="rating-star" />,
    reviews: "(156 reviews)",
    prevPrice: "800",
    newPrice: "150",
    company: "Cycle",
    color: "White",
    category: "Household",
  },
];

export default data;
